### ISSUE TITLE
issues with using MODBUS communication protocol

### ISSUE THREAD

**Issue by dadinn** [therealbstern/apcupsd#1]
I am experiencing some issues with using UPSTYPE MODBUS setting:
- getting constant broadcast messages about connection lost / restored.
- apcaccess doesn't show many of the device parameters (e.g. SERIALNO, MODEL, FIRMWARE, MANDATE)
- apcaccess shows wrong values for BCHARGE (1.7% instead of 100%), and doesn't show TIMELEFT. Since MBATTCHG is 5% and MINTIMEL is 3 minutes, this is possibly responsible for the **immediate shutdown when switching to battery power**.

My problems are very similar to the ones described [here](https://community.exchange.se.com/t5/APC-UPS-Data-Center-Backup/smt1000rmi2uc-and-modbus-protocol/td-p/297253).

I am using a APC UPS model [SMC1500I-2UC](https://www.apc.com/shop/ph/en/products/P-SMC1500I-2UC), with latest firmware (v04.1), and **apcupsd version 3.14.14**.

As the solution recommends in the above thread, when I disable MODBUS communication protocol on the UPS, and change back the apcupsd config to UPSTYPE=usb instead of modbus, and restart the daemon, the above issues are resolved. After this, switching to battery power doesn't cause immediate shutdown, and the BCHARGE, TIMELEFT, TONBATT, CUMONBATT, XONBATT, XOFFBATT parameters get updated as expected.

The problem is that using USB UPS Driver `apcaccess` doesn't return certain operational parameters (e.g. LINEV, MINLINEV, MAXLINEV, OUTPUTV, OUTCURNT, LINEFREQ, LOADPCT, AMBTEMP, etc) when not using MODBUS protocol. I know the UPS itself supports these parameters, as I can see them through SmartConnect on the APC online portal.

Also, most of the operations are not working with `apctest` when not using MODBUS protocol.

**Comment by therealbstern** [comment]
I understand your problems.

However, this fork is mostly because I was concerned that the source would disappear from the upstream website and I had nowhere obvious to publish the changes I made to fix build warnings.  I'm not especially familiar with the source code and am not sure where to start on fixing this issue.

I'd be happy to help integrate patches.
